@startuml
set namespaceSeparator ::

class "scheibner_app::algorithm::simulation.dart::ScheibnerSimulation" {
  {static} +void calcAdditionalData()
  {static} +dynamic simulate()
}

class "scheibner_app::commonWidgets::charts::chartData.dart::ChartType" {
  +int index
  {static} +List<ChartType> values
  {static} +ChartType simpleBarChart
  {static} +ChartType pieChart
  {static} +ChartType horizonalBarChart
}

"scheibner_app::commonWidgets::charts::chartData.dart::ChartType" o-- "scheibner_app::commonWidgets::charts::chartData.dart::ChartType"

class "scheibner_app::commonWidgets::charts::chartData.dart::ChartRow" {
  +List<Widget> charts
  +Widget widget
  +bool isWidget()
}

"scheibner_app::commonWidgets::charts::chartData.dart::ChartRow" o-- "flutter::src::widgets::framework.dart::Widget"

abstract class "scheibner_app::commonWidgets::charts::chartData.dart::ChartData" {
}

class "scheibner_app::commonWidgets::charts::chartData.dart::BarChartData" {
  +String year
  +double sales
  +Color color
}

"scheibner_app::commonWidgets::charts::chartData.dart::BarChartData" o-- "dart::ui::Color"
"scheibner_app::commonWidgets::charts::chartData.dart::ChartData" <|-- "scheibner_app::commonWidgets::charts::chartData.dart::BarChartData"

class "scheibner_app::commonWidgets::charts::chartData.dart::LinearSales" {
  +String year
  +int sales
  +Color color
}

"scheibner_app::commonWidgets::charts::chartData.dart::LinearSales" o-- "dart::ui::Color"
"scheibner_app::commonWidgets::charts::chartData.dart::ChartData" <|-- "scheibner_app::commonWidgets::charts::chartData.dart::LinearSales"

class "scheibner_app::commonWidgets::charts::chartFactory.dart::ChartFactory" {
  +double chartpadding
  +double cardpadding
  +double headingHeight
  +BoxConstraints constraints
  +BuildContext ctx
  +double getPaddingDiff()
  +double getHeight()
  +Widget getRow()
  +Widget getHeading()
}

"scheibner_app::commonWidgets::charts::chartFactory.dart::ChartFactory" o-- "flutter::src::rendering::box.dart::BoxConstraints"
"scheibner_app::commonWidgets::charts::chartFactory.dart::ChartFactory" o-- "flutter::src::widgets::framework.dart::BuildContext"

class "scheibner_app::commonWidgets::charts::chartInitializer.dart::ChartInitializer" {
  +Data meas
  +Data sim
  +List<Color> defaultColors
  +Map<String, MeasChartValue> values
  -List _getMaxDiffs()
  +List getResultChartViewData()
}

"scheibner_app::commonWidgets::charts::chartInitializer.dart::ChartInitializer" o-- "scheibner_app::data::data.dart::Data"

class "scheibner_app::commonWidgets::charts::chartInitializer.dart::MeasChartValue" {
  +String key
  +String localization
  +String shortcut
  +Color color
  +double measValue
  +double simValue
  +double getDiff()
  +double getPercentageDiff()
  -double _round()
}

"scheibner_app::commonWidgets::charts::chartInitializer.dart::MeasChartValue" o-- "dart::ui::Color"

class "scheibner_app::commonWidgets::charts::simOverviewChart.dart::SimOverviewChart" {
  +Widget createView()
  -List _getRange()
  -Series _getChartSeries()
  -ChartTitle _getTitle()
  -NumericAxisSpec _getXaxisOptions()
}

"scheibner_app::commonWidgets::charts::chartFactory.dart::ChartFactory" <|-- "scheibner_app::commonWidgets::charts::simOverviewChart.dart::SimOverviewChart"

class "scheibner_app::commonWidgets::charts::singleMeasChangeChart.dart::SingleMeasChangeChart" {
  +double wertAnzeigeWidth
  +List<BarChartData> data
  +MeasChartValue kennzahl
  +Widget getView()
  -Widget _getLeftSide()
  -Widget _getNewOldChartPercentValueWidget()
  -Widget _getNewOldChartValueWidget()
  -Widget _getRightSide()
}

"scheibner_app::commonWidgets::charts::singleMeasChangeChart.dart::SingleMeasChangeChart" o-- "scheibner_app::commonWidgets::charts::chartInitializer.dart::MeasChartValue"
"scheibner_app::commonWidgets::charts::chartFactory.dart::ChartFactory" <|-- "scheibner_app::commonWidgets::charts::singleMeasChangeChart.dart::SingleMeasChangeChart"

class "scheibner_app::components::threePointMenu.dart::ThreePointWidget" {
  +CustomPopupMenu createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::components::threePointMenu.dart::ThreePointWidget"

class "scheibner_app::components::threePointMenu.dart::CustomPopupMenu" {
  +String title
  +IconData icon
  -CustomPopupMenu _selectedChoices
  -void _select()
  +Widget build()
}

"scheibner_app::components::threePointMenu.dart::CustomPopupMenu" o-- "flutter::src::widgets::icon_data.dart::IconData"
"scheibner_app::components::threePointMenu.dart::CustomPopupMenu" o-- "scheibner_app::components::threePointMenu.dart::CustomPopupMenu"
"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::components::threePointMenu.dart::CustomPopupMenu"

class "scheibner_app::components::threePointMenu.dart::SelectedOption" {
  +CustomPopupMenu choice
  +Widget build()
}

"scheibner_app::components::threePointMenu.dart::SelectedOption" o-- "scheibner_app::components::threePointMenu.dart::CustomPopupMenu"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "scheibner_app::components::threePointMenu.dart::SelectedOption"

class "scheibner_app::data::appmodel.dart::AppModel" {
  -Profile _profile
  +Data getMeasurementData()
  +void setMeasurementData()
  +Data getSimulationData()
  +double getMeasValue()
  +double getSimValue()
  +void setSimValue()
  +void setSimulationData()
  +void simulate()
  +Profile getProfile()
  +void setProfile()
  +void setMeasurementId()
  +void setComment()
}

"scheibner_app::data::appmodel.dart::AppModel" o-- "scheibner_app::data::profile.dart::Profile"
"scoped_model::scoped_model.dart::Model" <|-- "scheibner_app::data::appmodel.dart::AppModel"

class "scheibner_app::data::data.dart::ValueInfo" {
  +String name
  +String unit
  +double lowerBound
  +double upperBound
}

class "scheibner_app::data::data.dart::Data" {
  {static} +List<ValueInfo> allValues
  {static} +List<ValueInfo> showable
  {static} +List<ValueInfo> modifiable
  {static} +List<ValueInfo> chartable
  {static} +Map<String, ValueInfo> valueInfo
  -DateTime _date
  -Map<String, dynamic> _values
  +String toJson()
  +void simulate()
  +double getValue()
  +void setValue()
}

class "scheibner_app::data::profile.dart::Profile" {
  +int id
  +String name
  +DateTime lastChanged
  +int serverId
  +Data meas
  +Data sim
  +String comment
  +Map toMap()
}

"scheibner_app::data::profile.dart::Profile" o-- "scheibner_app::data::data.dart::Data"

class "scheibner_app::data::profileList.dart::ProfileList" {
  -HashMap<int, String> _profiles
  +HashMap getProfiles()
  +void addProfile()
  +void deleteProfile()
}

"scheibner_app::data::profileList.dart::ProfileList" o-- "dart::collection::HashMap<int, String>"
"scoped_model::scoped_model.dart::Model" <|-- "scheibner_app::data::profileList.dart::ProfileList"

class "scheibner_app::helpers::database_helpers.dart::DatabaseHelper" {
  {static} -String _databaseName
  {static} -int _databaseVersion
  {static} +DatabaseHelper instance
  {static} -Database _database
  +Future<Database> database
  -dynamic _initDatabase()
  -Future _onCreate()
  +Future createProfile()
  +Future insertProfile()
  +Future deleteProfile()
  +Future deleteAllProfiles()
  +Future dropAllTables()
  +Future loadProfile()
  +Future updateProfileLastChanged()
  +Future saveProfile()
  +Future changeProfileName()
  +Future changeServerId()
  +Future changeMeasData()
  +Future changeSimData()
  +Future getRedProfileList()
}

"scheibner_app::helpers::database_helpers.dart::DatabaseHelper" o-- "scheibner_app::helpers::database_helpers.dart::DatabaseHelper"
"scheibner_app::helpers::database_helpers.dart::DatabaseHelper" o-- "sqflite::sqlite_api.dart::Database"

class "scheibner_app::helpers::helperfunctions.dart::Helper" {
  {static} +double EPS
  {static} +String valToString()
  {static} +Text createDifferenceText()
  {static} +String getCurrentProfileName()
}

class "scheibner_app::helpers::measurementService.dart::ApiService" {
  +Future getMeasurementFromId()
  +Data getMeasurementFromJson()
  -Data _createMeasurementFromJson()
  -String _checkIfObjIsValid()
}

class "scheibner_app::helpers::scheibnerException.dart::ScheibnerException" {
  +String msg
  +String toString()
}

"dart::core::Exception" <|-- "scheibner_app::helpers::scheibnerException.dart::ScheibnerException"

class "scheibner_app::localization::application.dart::Application" {
  {static} -Application _application
  +List<String> supportedLanguages
  +List<String> supportedLanguagesCodes
  +(Locale) → void onLocaleChanged
  +Iterable supportedLocales()
}

"scheibner_app::localization::application.dart::Application" o-- "scheibner_app::localization::application.dart::Application"
"scheibner_app::localization::application.dart::Application" o-- "scheibner_app::localization::application.dart::(Locale) → void"

class "scheibner_app::localization::app_translations.dart::AppTranslations" {
  +Locale locale
  {static} -Map _localisedValues
  +dynamic currentLanguage
  {static} +AppTranslations of()
  {static} +Future load()
  +String text()
}

"scheibner_app::localization::app_translations.dart::AppTranslations" o-- "dart::ui::Locale"

class "scheibner_app::localization::app_translations_delegate.dart::AppTranslationsDelegate" {
  +Locale newLocale
  +bool isSupported()
  +Future load()
  +bool shouldReload()
}

"scheibner_app::localization::app_translations_delegate.dart::AppTranslationsDelegate" o-- "dart::ui::Locale"
"flutter::src::widgets::localizations.dart::LocalizationsDelegate<T>" <|-- "scheibner_app::localization::app_translations_delegate.dart::AppTranslationsDelegate"

class "scheibner_app::main.dart::ScheibnerApp" {
  +ScheibnerAppState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::main.dart::ScheibnerApp"

class "scheibner_app::main.dart::ScheibnerAppState" {
  -AppTranslationsDelegate _newLocaleDelegate
  +void initState()
  +Widget build()
  +void onLocaleChange()
  -ScopedModel _scopedModelWrapper()
}

"scheibner_app::main.dart::ScheibnerAppState" o-- "scheibner_app::localization::app_translations_delegate.dart::AppTranslationsDelegate"
"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::main.dart::ScheibnerAppState"

class "scheibner_app::pages::dataInputPage.dart::DataInputPage" {
  +_DataInputState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::pages::dataInputPage.dart::DataInputPage"

class "scheibner_app::pages::dataInputPage.dart::_DataInputState" {
  +String barcode
  +Data measurementData
  +ApiService apiService
  -TextEditingController _textFieldController
  +bool isLoading
  +dynamic loadingSubScription
  +void initState()
  +Widget build()
  -Widget _createListView()
  -Widget _makeNoProfilesWidget()
  -Widget _createMeasValueList()
  -void _displayMeasIdDialog()
  +void processMeasurement()
  +Future scan()
  -void _showToast()
}

"scheibner_app::pages::dataInputPage.dart::_DataInputState" o-- "scheibner_app::data::data.dart::Data"
"scheibner_app::pages::dataInputPage.dart::_DataInputState" o-- "scheibner_app::helpers::measurementService.dart::ApiService"
"scheibner_app::pages::dataInputPage.dart::_DataInputState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::pages::dataInputPage.dart::_DataInputState"

class "scheibner_app::pages::preferencesPage.dart::PreferencesPage" {
  +PreferencesPageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::pages::preferencesPage.dart::PreferencesPage"

class "scheibner_app::pages::preferencesPage.dart::PreferencesPageState" {
  {static} +List<String> languagesList
  {static} +List<String> languageCodesList
  +Map languagesMap
  +String label
  +void initState()
  +void onLocaleChange()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::pages::preferencesPage.dart::PreferencesPageState"

class "scheibner_app::pages::profilePage.dart::ReducedProfile" {
  +int profileID
  +String name
  +DateTime lastChanged
}

class "scheibner_app::pages::profilePage.dart::ProfilePage" {
  +_ProfiletState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::pages::profilePage.dart::ProfilePage"

class "scheibner_app::pages::profilePage.dart::_ProfiletState" {
  -List<ReducedProfile> _profiles
  +DatabaseHelper dbHelper
  -TextEditingController _textFieldController
  +void initState()
  -void _reloadProfiles()
  +Widget build()
  -Widget _makeContent()
  -Widget _makeNoProfilesWidget()
  -Widget _makeCard()
  -String _dateToString()
  -dynamic _openProfile()
  -dynamic _displayNewProfileNameDialog()
  -Widget _getDeleteIconColumn()
  -void _initalizePreferencesValues()
}

"scheibner_app::pages::profilePage.dart::_ProfiletState" o-- "scheibner_app::helpers::database_helpers.dart::DatabaseHelper"
"scheibner_app::pages::profilePage.dart::_ProfiletState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::pages::profilePage.dart::_ProfiletState"

class "scheibner_app::pages::resultsChartView.dart::ChartView" {
  +List<(dynamic, dynamic) → Widget> listItems
  +List<String> legendItems
  +double legendwidth
  +Widget build()
  +Widget buildLegend()
  +Widget buildCharts()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "scheibner_app::pages::resultsChartView.dart::ChartView"

class "scheibner_app::pages::resultsPage.dart::ResultsPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "scheibner_app::pages::resultsPage.dart::ResultsPage"

class "scheibner_app::pages::resultsSaveView.dart::SaveView" {
  +State createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::pages::resultsSaveView.dart::SaveView"

class "scheibner_app::pages::resultsSaveView.dart::_SaveViewState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::pages::resultsSaveView.dart::_SaveViewState"

class "scheibner_app::pages::resultsTableView.dart::TableView" {
  +Widget build()
  -Widget _createSimValueList()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "scheibner_app::pages::resultsTableView.dart::TableView"

class "scheibner_app::pages::simulationPage.dart::SimulationPage" {
  +State createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "scheibner_app::pages::simulationPage.dart::SimulationPage"

class "scheibner_app::pages::simulationPage.dart::_SimulationState" {
  -Map<String, TextEditingController> _controllers
  -Map<String, double> _sliderValues
  +Widget build()
  -List _createSliderList()
  -List _createTextBoxList()
  +void dispose()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "scheibner_app::pages::simulationPage.dart::_SimulationState"


@enduml